server:
  port: 8088
  servlet:
    context-path: /authority

spring:
  mvc:
    servlet:
      load-on-startup: 100
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: fzw940816
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5    #初始大小
      minIdle: 5        #最小值
      maxActive: 100    #最大值
      maxWait: 60000    #获取连接等待超时时间
      max-pool-prepared-statement-per-connection-size: 20
      timeBetweenEvictionRunsMillis: 60000    #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000     #一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true   #设置为true,防止取到的连接不可用
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j  #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
  redis:
    host: 39.105.215.122
    port: 6379
    password: Fzw940816!
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
    database: 0
#  session:
#    store-type: redis
#    redis:
#      flush-mode: on_save
#      namespace: myproject
#    timeout: PT10M



filter:
  stat:
    log-slow-sql: true
    db-type: mysql
    slow-sql-millis: 5000
  wall:
    enabled: true
    db-type: mysql
    config:
      delete-allow: true
      drop-table-allow: false
  web-stat-filter:
    enabled: true
    url-pattern: /*
    exclusions: /druid/*
  stat-view-servlet:
    enabled: true
    url-pattern: /druid/*
    reset-enable: false
    login-username: admin
    login-password: admin
    allow: 127.0.0.1
    deny: #访问黑名单

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/fzw/eland/dao/**/*.xml

logging:
  config: classpath:log4j2-dev.xml

img:
  BASE_IMG_URL: D:/jtdrImg/         #图片访问地址
  BASE_IMG_ADDRESS: D:/jtdrImg/    #图片上传地址

